global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'federate'
    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
       - '{job="prometheus"}'
       - '{__name__=~"job:.*"}'

    static_configs:
    - targets:
      - '192.168.0.89:30900'


