global:
  scrape_interval: "15s"
  evaluation_interval: "15s"

scrape_configs:
  honor_labels: true
  metrics_path: '/federate'

- job_name: "prometheus"
  scrape_interval: "15s"
  metrics_path: "/metrics"
  static_configs:
  - targets: ["localhost:9090"]

- job_name: "K8s Metrics"
  scrape_interval: "15s"
  metrics_path: "/metrics"
  static_configs:
  - targets: ["8.208.93.32:9100"]

